#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/todo_list_db
#    username: impactTest
#    password: Spring@123
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
